// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://docs.astralapp.io/legal/terms",
        "contact": {
            "name": "DevOps Team",
            "url": "https://astralapp.io",
            "email": "devops@astralapp.io"
        },
        "license": {
            "name": "MPL-2.0",
            "url": "https://opensource.org/licenses/MPL-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "api.astralapp.io",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Astral API",
	Description:      "The official API for Astral Services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
